[build-system]
requires = [
    'setuptools',
    'wheel',
    'tortoise-orm'
]

build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80